# For security reasons we use environment variables, so we avoid having secrets in git.
# We reuse the environment variables set for using terraform

aws:
  region: "{{ lookup('env','TF_VAR_region') }}"
  access_key: "{{ lookup('env','TF_VAR_access_key') }}"
  secret_key: "{{ lookup('env','TF_VAR_secret_key') }}"
